name: untitled2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  foldable_list: ^1.0.0
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.7
  cached_network_image: ^3.1.0
  flutter_carousel_slider: ^1.0.8
  nb_utils: ^4.4.2
  connectivity_plus: ^1.1.0
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  simple_animations: ^3.1.1
  shared_preferences: ^2.0.6
  readmore: ^2.1.0
  auto_size_text_pk: ^3.0.0
  flutter_add_to_cart_button: ^1.0.0+1
  shimmer: ^2.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  rolling_nav_bar: ^0.0.5-nullsafety.3
  sizer: ^2.0.13
  flutter_sizer: ^1.0.3
  pull_to_refresh: ^2.0.0
  expandable: ^5.0.1
  outline_search_bar: ^2.2.0
  flutter_staggered_grid_view: ^0.4.0
  delayed_display: ^2.0.0
  url_launcher: ^6.0.9
  lazy_load_scrollview: ^1.3.0
  flutter_automation: ^2.0.0
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  double_back_to_close_app: ^2.0.1
  flutter_phoenix: ^1.0.0
  loader_overlay: ^2.0.2+1
  marquee: ^2.2.0
  awesome_dropdown: ^0.0.4
  roundcheckbox: ^2.0.2+1
  bottom_picker: ^1.0.1
  webview_flutter: ^2.0.12
  progress_indicators: ^1.0.0
  badges: ^2.0.1
    #  group_button: ^3.1.0
  select_dialog: ^2.0.0
  intl: ^0.17.0
  dio: ^4.0.0
    #  adaptive_dialog: ^1.1.0
  rflutter_alert: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  provider: ^6.0.0
  flutter_overlay: ^1.0.0
  progress_loading_button: '^1.0.0'
  get_it: ^7.2.0
  async: ^2.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: 'appIcon/playstore.png'
  image_path_ios: "appIcon/playstore.png"
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - MyAssets/asset1.jpg
    - MyAssets/asset2.jpg
    - MyAssets/asset3.jpg
    - MyAssets/asset4.jpg
    - MyAssets/asset5.jpg
    - MyAssets/livinghall.jpg
    - MyAssets/dininghall.jpg
    - MyAssets/bedroom.jpg
    - MyAssets/logo.png
    - MyAssets/top-background.png
    - MyAssets/okay.jpeg
    - MyAssets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HeartIcon
      fonts:
        - asset: MyAssets/icons/HeartIcon.ttf

    - family: MyHeartIcon
      fonts:
        - asset: MyAssets/icons/MyHeartIcon.ttf
    - family: MyFlutterApp
      fonts:
        - asset: MyAssets/icons/MyFlutterApp.ttf
    - family: Facebook
      fonts:
        - asset: MyAssets/icons/Facebook.ttf
    - family: Forward_arrow
      fonts:
        - asset: MyAssets/icons/Forward_arrow.ttf
    - family: Arial
      fonts:
        - asset: MyAssets/fonts/arial.ttf
    - family: Remove
      fonts:
        - asset: MyAssets/icons/Remove.ttf
    - family: Orders
      fonts:
        - asset: MyAssets/icons/Orders.ttf
    - family: ChangePassword
      fonts:
        - asset: MyAssets/icons/ChangePassword.ttf
    - family: Address
      fonts:
        - asset: MyAssets/icons/Address.ttf
    - family: Youtube
      fonts:
        - asset: MyAssets/fonts/Youtube.ttf
#    - family: Monstserrat
#      fonts:
#        - asset: MyAssets/fonts/UserFont/MonstserratBold.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratBoldItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratExtraBoldItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratExtraBold.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratExtraLight.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratExtraLightItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratLight.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratLightItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratMedium.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratMediumItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratRegular.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratSemiBold.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratSemiBoldItalic.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratThin.ttf
#        - asset: MyAssets/fonts/UserFont/MonstserratThinItalic.ttf
#    - family: Monstserrat Light
#      fonts:
#        - asset: MyAssets/fonts/Monstserrat_Light.ttf
#         - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
